
language: ruby

install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  # - export PATH=/Users/baiying/pandoc:/Users/baiying/.rvm/gems/ruby-2.4.0/bin:/Users/baiying/.rvm/gems/ruby-2.4.0@global/bin:/Users/baiying/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/baiying/.rvm/bin:/Users/baiying/.rvm/bin
  # - mkdir /Users/baiying/pandoc
  # - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  # - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
  #     -d /Users/baiying/pandoc
  # - chmod +x /Users/baiying/pandoc/pandoc
  # - pandoc --version

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: EXAMPLE

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME=YOUR_USERNAME GIT_EMAIL=YOUR_EMAIL GH_TOKEN=YOUR_TOKEN'
