# Site settings
theme: jekyll-theme-minimal
title: Yongsheng Yu's Homepage
header-img: img/post-bg-swift2.jpg
email: yongsheng.yu@hdr.mq.edu.au
description: "人，要有思想和格局，不能人云亦云，也不能亦步亦趋."
keyword: "yuyongsheng, Data Mining, Knowledge Graph "
url: "https://yuyongsheng1990.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you are going to be!"
sidebar-avatar: img/profile_1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
# zhihu_username:     于永胜
github_username:    yuyongsheng1990
# facebook_username:
# jianshu_username:
twitter_username:   YongshengYu1990




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: c0d49813b1ec6270ff5a                            #生成的clientID
  clientSecret: 75ecfd4146c38b51464e7b171f2628e089b76133    #生成的clientSecret
  repo: yuyongsheng1990.github.io    #仓库名称
  owner: yuyongsheng1990    #github用户名
  admin: yuyongsheng1990
  id: 'window.location.pathname'
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-135270091-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
